name: Build AnomaMali UMD Layer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Android NDK
      uses: ndk-ndk/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Build Shared Library (.so)
      run: |
        $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang \
        -shared -fPIC -O3 \
        Anoma_Mali.c \
        -Iumd \
        -o libanoma_mali.so \
        -lvulkan

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: libanoma_mali.so
        path: libanoma_mali.so
        
